services:
  amaris-postgres:
    image: "postgres:13-alpine"
    container_name: amaris-postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
#    TODO TEMPORAL
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - amaris-postgres-data:/var/lib/postgresql/data
      - './bootstrap/init.sql:/docker-entrypoint-initdb.d/init.sql'
    networks:
      - amaris-beer-network

  amaris-redis:
    image: "redis:alpine"
    container_name: amaris-redis
    ports:
      - "6379:6379"
    #    TODO TEMPORAL
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - amaris-beer-network

  amaris-beer-service:
    build:
      context: ../amaris-beer
    container_name: amaris-beer-service
    ports:
      - "3001:3001"
    #    TODO TEMPORAL
    env_file:
      - .env
    depends_on:
      - amaris-postgres
      - amaris-redis
    networks:
      - amaris-beer-network

  amaris-beer-price-service:
    build:
      context: ../amaris-beer-price
    container_name: amaris-beer-price-service
    ports:
      - "3002:3002"
    #    TODO TEMPORAL
    env_file:
      - .env
    depends_on:
      - amaris-beer-service
      - amaris-redis
      - amaris-postgres
    networks:
      - amaris-beer-network

networks:
  amaris-beer-network:
    name: amaris-beer-network

volumes:
  amaris-postgres-data:
